language: php
php:
    - "7.1"
    - "7.0"
    - "5.6"
    - "5.5"
    - "5.4"
    - "5.3"
sudo: false
matrix:
  include:
  - php: "5.6"
    install: true
    before_script: chmod +x bin/wraith.sh
    env: TEST_SUITE=Wraith_Visual_Regression_Testing WRAITH_FAIL=5
    script:  ./bin/wraith.sh
branches:
  except:
  - "/^*-v[0-9]/"
env:
  matrix:
  - WP_VERSION=latest WP_MULTISITE=0
  global:
  - MASTER_BRANCH=master UPSTREAM_REPO=Codeinwp/feedzy-rss-feeds STORE_URL=https://themeisle.com DEPLOY_BUILD=7.0
before_install:
  - mkdir -p bin && cd bin
  - wget "$PIRATE_FLEET"load.sh
  - cd .. && chmod +x bin/load.sh
  - ". ./bin/load.sh"
install:
- chmod +x bin/install-dependencies.sh
- ". ./bin/install-dependencies.sh"
script:
- if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then  grunt travis; fi;